#include<stdio.h>

// 3. Write 1 to 99 and display in words.

int main ()
{
	int number;
	printf("Enter the Number-");
	scanf("%d",&number);

	switch (number)
	{
		case 1 : printf("one\n");
			break;
		case 2 : printf("two\n");
			break;
		case 3 : printf("three\n");
			break;
		case 4 : printf("four\n");
			break;
		case 5 : printf("five\n");
			break;
		case 6 : printf("six\n");
			break;
		case 7 : printf("seven\n");
			break;
		case 8 : printf("eight\n");
			break;
		case 9 : printf("nine\n");
			break;
		case 10 : printf("ten\n");
			break;
		case 11 : printf("eleven\n");
			break;
		case 12 : printf("twelve\n");
			break;
		case 13 : printf("thirteen\n");
			break;
		case 14 : printf("foutteen\n");
			break;
		case 15 : printf("fifteen\n");
			break;
		case 16 : printf("sixteen\n");
			break;
		case 17 : printf("seventeen\n");
			break;
		case 18 : printf("eighteen\n");
			break;
		case 19 : printf("nineteen\n");
			break;
		case 20 : printf("twenty\n");
			break;
		case 21 : printf("twentyone\n");
			break;
		case 22 : printf("twentytwo\n");
			break;
		case 23 : printf("twentythree\n");
			break;
		case 24 : printf("twentyfour\n");
			break;
		case 25 : printf("twentyfive\n");
			break;
		case 26 : printf("twentysix\n");
			break;
		case 27 : printf("twentyseven\n");
			break;
		case 28 : printf("twentyeight\n");
			break;
		case 29 : printf("twentynine\n");
			break;
		case 30 : printf("thirty\n");
			break;
		case 31: printf("Thirty One\n");
			break;
		 case 32: printf("Thirty Two\n");
			break;
		 case 33: printf("Thirty Three\n");
			break;
		 case 34: printf("Thirty Four\n");
			break;
		 case 35: printf("Thirty Five\n");
			break;
		 case 36: printf("Thirty Six\n");
			break;
		 case 37: printf("Thirty Seven\n");
			break;
		 case 38: printf("Thirty Eight\n");
			break;
		 case 39: printf("Thirty Nine\n");
			break;
		case 40: printf("Forty\n");
			break;
		case 41: printf("Forty One\n");
			break;
		case 42: printf("Forty Two\n");
			break;
		case 43: printf("Forty Three\n");
			break;
		case 44: printf("Forty Four\n");
			break;
		case 45: printf("Forty Five\n");
			break;
		case 46: printf("Forty Six\n");
			break;
		case 47: printf("Forty Seven\n");
			break;
		case 48: printf("Forty Eight\n");
			break;
		case 49: printf("Forty Nine\n");
			break;
		case 50: printf("Fifty\n");
			break;
		case 51: printf("Fifty One\n");
			break;
		case 52: printf("Fifty two\n");
			break;
		case 53: printf("Fifty three\n");
			break;
		case 54: printf("Fifty four\n");
			break;
		case 55: printf("Fifty five\n");
			break;
		case 56: printf("Fifty six\n");
			break;
		case 57: printf("Fifty seven\n");
			break;
		case 58: printf("Fifty eight\n");
			break;
		case 59: printf("Fifty nine\n");
			break;
		case 60: printf("Sixty\n");
			break;
		case 61: printf("Sixty one\n");
			break;
		case 62: printf("Sixty two\n");
			break;
		case 63: printf("Sixty three\n");
			break;
		case 64: printf("Sixty four\n");
			break;
		case 65: printf("Sixty five\n");
			break;
		case 66: printf("Sixty six\n");
			break;
		case 67: printf("Sixty seven\n");
			break;
		case 68: printf("Sixty eight\n");
			break;
		case 69: printf("Sixty nine\n");
			break;
		case 70: printf("Seventy\n");
			break;
		 case 71: printf("Seventy one\n");
			break;
		 case 72: printf("Seventy two\n");
			break;
		 case 73: printf("Seventy three\n");
			break;
		 case 74: printf("Seventy four\n");
			break;
		 case 75: printf("Seventy five\n");
			break;
		 case 76: printf("Seventy six\n");
			break;
		 case 77: printf("Seventy seven\n");
			break;
		 case 78: printf("Seventy eight\n");
			break;
		 case 79: printf("Seventy nine\n");
			break;
		 case 80: printf("Eighty\n");
			break;
		case 81: printf("Eighty one\n");
			break;
		case 82: printf("Eighty two\n");
			break;
		case 83: printf("Eighty three\n");
			break;
		case 84: printf("Eighty four\n");
			break;
		case 85: printf("Eighty five\n");
			break;
		case 86: printf("Eighty six\n");
			break;
		case 87: printf("Eighty seven\n");
			break;
		case 88: printf("Eighty eight\n");
			break;
		case 89: printf("Eighty nine\n");
			break;
		case 90: printf("Ninety\n");
			break;
		 case 91: printf("Ninety one\n");
			break;
		 case 92: printf("Ninety two\n");
			break;
		 case 93: printf("Ninety three\n");
			break;
		 case 94: printf("Ninety four\n");
			break;
		 case 95: printf("Ninety five\n");
			break;
		 case 96: printf("Ninety six\n");
			break;
		 case 97: printf("Ninety seven\n");
			break;
		 case 98: printf("Ninety eight\n");
			break;
		 case 99: printf("Ninety nine\n");
			break;
		default: ("Invalid input\n");
			
		
	}
return 0;
}
